ALTER TABLE t_p45794133_smartmach_platform_p.parts
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Прочее',
  ADD COLUMN IF NOT EXISTS is_template BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS dimensions TEXT,
  ADD COLUMN IF NOT EXISTS weight_kg NUMERIC(10,3),
  ADD COLUMN IF NOT EXISTS standard TEXT;
