CREATE TABLE t_p45794133_smartmach_platform_p.assembly_nodes (
  id                SERIAL PRIMARY KEY,
  assembly_id       INTEGER NOT NULL REFERENCES t_p45794133_smartmach_platform_p.assemblies(id),
  parent_id         INTEGER REFERENCES t_p45794133_smartmach_platform_p.assembly_nodes(id),
  path              TEXT NOT NULL DEFAULT '',
  position_no       INTEGER,
  sort_order        INTEGER NOT NULL DEFAULT 0,
  node_type         TEXT NOT NULL DEFAULT 'part' CHECK (node_type IN ('assembly','part','standard','material','purchased','fastener')),
  code              TEXT NOT NULL,
  name              TEXT NOT NULL,
  revision          TEXT NOT NULL DEFAULT 'A',
  qty               NUMERIC(12,4) NOT NULL DEFAULT 1,
  unit              TEXT NOT NULL DEFAULT 'шт',
  material          TEXT,
  weight_kg         NUMERIC(12,4),
  total_weight_kg   NUMERIC(12,4),
  dimensions        TEXT,
  surface_finish    TEXT,
  heat_treatment    TEXT,
  tolerance_class   TEXT,
  fit_type          TEXT,
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','in_design','checking','approved','production','issue')),
  part_id           INTEGER REFERENCES t_p45794133_smartmach_platform_p.parts(id),
  child_assembly_id INTEGER REFERENCES t_p45794133_smartmach_platform_p.assemblies(id),
  notes             TEXT,
  issue_flag        BOOLEAN NOT NULL DEFAULT FALSE,
  issue_note        TEXT,
  supplier          TEXT,
  supplier_code     TEXT,
  lead_time_days    INTEGER,
  standard_ref      TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
)